### ISSUE TITLE
当ember-data提供的高级API不适用自己，如何扩展自己的Function

### ISSUE THREAD

**Issue by Faiz2** [very-geek/help#2]
**您好：**
我是个新手，最近刚接触ember，在自己捣鼓ember过程中遇到个疑问

1. 如果ember-data提供的高级API不适用当时的场景，如何自己扩展
2. 扩展后如何与adapter相结合使用，可以像其他Function一样override

现在我是通过service 重新extend DS.Store，在里面新增自己的function 虽然能通过`store.`的方式调用到，但是不能与adapter相结合使用。

以下是我的code：

```js
//service.js
export default DS.Store.extend({
    adapter:'pharbers-adapter',
    init() {
        this._super(...arguments)
        window.console.info("DS.Store")
    },
    queryObject(type, query) {
        // debugger
        const store = this;
        const typeClass = store.modelFor(type);
        const adapter = store.adapterFor('pharbers-adapter');
        const serializer = store.serializerFor(type);
        const url = adapter.buildURL(type);
        const ajaxPromise = adapter.ajax(url, 'POST', { data: JSON.stringify(query) });
        return ajaxPromise.then(function(rawPayload) {
            let extractedPayload = serializer.extract(store, typeClass, rawPayload, 'query');
            return store.push(typeClass, extractedPayload);
        });
    }

});
```
```js
//adapter.js
export default DS.RESTAdapter.extend({
    defaultSerializer: '-default',
    host: 'http://127.0.0.1:9000',
    queryObject(type, query) {
        // debugger,
        console.info(123)
        let header = {
            dataType: 'json',
            contentType: 'application/json,charset=utf-8',
            Accept: 'application/json,charset=utf-8',
            data: query
        };
        return this.ajax(singularize(this.buildURL(type.modelName)), 'POST', header);
    }
});
```

**现在调用this.store.queryObject虽然能成功，但不是我想要的效果，我期望的效果是，adapter有重写就走adapter里的，这个时候会打印`123`，没有重写就走默认的Function。**

**这个问题困扰了我好久，可以提供大体的思路吗或者有什么Demo可以让我参考下？谢谢**

**Comment by nightire** [comment]
你所描述的大体上是你“怎么做”的，但是我首先要关心的是你“为什么而做”；明确了意图之后，才能作出更好的代码设计。关于“为什么”，我有几个小问题先摆出来：

1. `store.queryRecord` 已经有了，你自己写的 `store.queryObject` 是为了什么目的呢？`store.queryRecord` 有什么问题不能满足你的需求吗？
2. _query_ 的语义是查询，但我注意到你在 `store.queryObject` 的代码实现中却是用了 `POST` 请求，这背后的理由是什么呢？

我大致能想像出你写 `store.queryObject` 的理由，以上问题是为了进一步求证。

---

下面，抛开具体的需求不谈，我简单来说说一些关于 ember-data 的一般性概念。

首先，ember-data 主要做了这么几件事情：

1. Adapter（适配器）：处理所有对外的 HTTP 请求。在代码层面，不会直接通过 adapter 来发出请求，而是通过 store 提供的接口将请求代理给 adapter，但是 store 不关心请求的具体实现，它只提供接口并将请求的细节传递给 adapter，具体发送请求的逻辑是在 adapter 内部实现的。

2. Serializer（序列化）：Adapter 发请求/收响应时需要对 payload（数据载荷）进行序列化的操作，简单来说就是 Object 和 JSON 之间的相互转换，以及 Object 的数据结构的转换。这部分的工作 adapter 会代理给配套的 serializer 来处理。

3. Store（数据仓库）：用户在本地创建的数据以及通过 adapter 请求到的数据都会按照 Model（数据模型）分门别类的存储在一个本地的内存式的数据仓库里，这个仓库可以看作一个简易版的关系型数据库，可以对数据进行创建/修改/查询/删除/关系处理等操作，这些本地化的操作都由一个统一的 interface（接口）来实现，也就是 store；同时，一些本地操作也有对应的持久化请求（也就是发送给服务器的请求），store 也负责代理这些请求给对应的 adapter——这是我在 1. 里所描述的部分。

有了这些基本的背景知识打底，咱们可以来回顾一下你的具体代码实现了（先不考虑这个代码设计是否合理的问题）：

`store.queryObject` 做了太多非自己职责的事情，可以用 `store.queryRecord` 来做[参照物](https://github.com/emberjs/data/blob/v3.0.0/addon/-private/system/store.js#L1390)，最最起码的一点：Ajax 请求是怎么发出去的，这个细节不应该暴露在 store 这一层，而是应该代理给 adapter 来做（这也是造成你很难去做 override 的根本原因，如果你保持 store 只是代理请求的接口，而有 adapter 负责处理具体的请求逻辑，那么就很容易通过 extend adapter 来进行 override 了）。

`store.queryRecord` 也没有直接代理给 adapter，而是用了一个工具函数来[处理代理的过程](https://github.com/emberjs/data/blob/v3.0.0/addon/-private/system/store/finders.js#L173)，这么做主要是两个原因（好处）：一是解耦，独立的工具函数也很容易单元测试；二是方便重用。你扩展的时候要不要这么做取决于实际情况，倒也不必强求。

**Comment by Faiz2** [comment]
@nightire 感谢您百忙之中解答我的问题，关于您的2个疑问是这样子的

1. 其实使用queryRecord对于我来说可以解决我的部分问题，其他的也可以通过adapter override和Serializer进行特殊的处理，问题就在于名字，在项目中运用后，我们老大觉得Ember给出的命名不适用于现在的业务的命名，说白了就是命名的问题，于是就有了需要自己实现符合公司整体命名的CURD的需求，对于上面的queryObject只是我做测试的时候写的，并不能代表。

2. 关于POST问题是这样子的，当时后端开发并没有考虑对外开放接口，除了页面与资源是GET，剩余的数据请求都是POST，还有中间的通讯协议是我们自己定的，返回的也比较杂乱（估计在二次重构的时候会使用标准），这也就是为什么您看到我用的是query但内部是POST的原因了。

看了您的回复更加清晰了，谢谢您的指点。

**Comment by nightire** [comment]
@Faiz2 你可以加 QQ 群 242650456，最近也有人问和你的需求类似的问题，有更多人在一起讨论会更有帮助的。

**Comment by Faiz2** [comment]
@nightire 我已经悄悄的加入了，😄

**Comment by qianthinking** [comment]
不知道是不是类似的问题，我们服务端是Java，你懂的camelCase，ember-data在Serializer可重写payloadTypeFromModelName, modelNameFromPayloadType, 但是要打开相应的FEATURE: ds-payload-type-hooks，另外还有keyForAttribute, keyForRelationship

**Comment by Faiz2** [comment]
@qianthinking 你好：
我也是刚开始学Ember的小白，不知道能不能给帮助。
首先我有这个需求是因为命名不符合公司业务的问题导致需要新增扩展自己的一套东西，实现与源码和nightire说的几乎一模一样,只有在个别的query中添加了我们公司自己的逻辑。
具体请求都在Adapter中实现，返回的数据虽然不标准但都在Serializer中去解析成Ember想要的东西，我当时实现时，把整个store和相关看了一遍，[传送门](https://github.com/emberjs/data/blob/v3.0.0/addon/-private/system/store.js#L5)，希望对你有帮助

**Comment by qianthinking** [comment]
@Faiz2 谢谢你的好意，是我没说清楚，我本意是想说，如果只是因为命名的问题，ember-data开放了一些Serializer级别的API供你定制类型名称，属性名称以及关联名称，感觉覆盖了大部分情况（如果不是全部的话），我们就是这样解决的，不知道适不适合你们。

**Comment by nightire** [comment]
@qianthinking 需要打开这个 FEATURE，是因为以前类似的 hook 都叫 `keyFor...`，然后后来有一次重构。但是基于 ember 的理念，重构之后不会立刻废弃过去的 API，所以把新的 hook 放在 FEATURE 后面，一段时间之后逐渐 deprecate 了旧的 API，才会把 FEATURE 变成 default。
